"""add project priority

Revision ID: a734638f596b
Revises: b626077f1e75
Create Date: 2026-09-18 19:36:35.511665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a734638f596b'
down_revision: Union[str, Sequence[str], None] = 'b626077f1e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ### 
    op.add_column('projects', sa.Column('priority', sa.String(length=20), nullable=True))
    op.execute("UPDATE projects SET priority = 'Medium' WHERE priority IS NULL")
    op.alter_column('projects', 'priority', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'priority')
    # ### end Alembic commands ###
